services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-network

  app:
    build: .
    image: my-backend-image
    container_name: api_backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - api-network

volumes:
  mysqldata:

networks:
  api-network:
    driver: bridge